### ISSUE TITLE
Página 404

### ISSUE THREAD

**Issue by Pillin** [JSConfCL/2024#24]
## Descripción

**Desktop**
![Image](https://github.com/JSConfCL/2024/assets/759231/382a7fa2-57c5-4ebb-b96f-720100b1c02e)

**Mobile**
![Image](https://github.com/JSConfCL/2024/assets/759231/a17821db-369b-4d2e-983a-6decd0ab5f36)

## Criterios de Aceptación
- [ ] La Página tiene que ser una componente agnóstica con sub componentes agnósticos que reciba la información que va a renderear desde Sanity.
- [ ] Tiene que soportar mobile y desktop
- [ ] La componente tiene que verse visualmente como el diseño

**Comment by geekhadev** [comment]
Hola, he colaborado en esta tarea, pero me falta todavía en el PR dejo los detalles de lo que me falta ojalá algún capo me pueda ayudar a completarla y así poder seguir apoyando.

**Comment by Pillin** [comment]
Hola @geekhadev Genial, muchas gracias, podrías asignarte a la tarea y enlazar el pr al issue, así no se realiza doble trabajo

**Comment by geekhadev** [comment]
> Hola [@geekhadev](https://github.com/geekhadev) Genial, muchas gracias, podrías asignarte a la tarea y enlazar el PR al ISSUE, así no se realiza doble trabajo

No sé como hacerlo, he trabajado en varios temas, y he tenido que dejar los comentarios manuales, porque no se como asignarme la ISSUE

**Comment by geekhadev** [comment]
Saludos a los revisores, intente dar con el diseño 100% el figma pero logré llevarlo a este punto, pido revisión de este comentario a ver si aprueba para implementar el cambio. Gracias de antemano.

Dejo igual la propuesta de código por si tienen al©un alcance:

```css
.border-gradient {
  border: 1px solid;
  border-image-slice: 10;
  border-width: 3px;
  border-image-source: linear-gradient(to top right, transparent, #F0E040);
  border-radius: 5px;
  -webkit-mask: 
    linear-gradient(#fff 0 0) content-box, 
    linear-gradient(#fff 0 0);
  pointer-events: none;
}
```


![Image](https://github.com/JSConfCL/2024/assets/499907/3e6f14ed-ab89-4559-a5f9-8bc16505b319)

![Image](https://github.com/JSConfCL/2024/assets/499907/9fd51427-b6f8-423c-b084-97631b7651c7)
